language: python
python:
  - "2.7"
# command to install dependencies
install:
    - "pip install tox coveralls pytest-travis-fold"
# command to run tests
script: tox
after_success:
  - coveralls
# preserve our API requests (currently limited to 50 per day)
cache:
  directories:
  - .requests_cache